language: node_js
node_js:
  - 0.11
addons:
    - googlechrome
before_script:
  - cd sdk
  - npm install -d
  - export CHROME_BIN=/usr/bin/google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
branches:
    only:
        - web-apps-sdk-ui
sudo: false